version: "3.6"

services:

  app:
    platform: linux/amd64
    image: ghcr.io/{{elsiniestra}}/{{python-backend-template}}:latest  # TODO: cookiecutter
    restart: on-failure
    healthcheck:
      test: curl --fail http://0.0.0.0:5432 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    env_file:
      - ../.env
    ports:
      - "8000:8000"
